
version: '3.1'
services:
  burner:
    build:
      context: .
      dockerfile: wisedocs.Dockerfile
    container_name: wisedocs-${EDITION}
    restart: "unless-stopped"
    ports:
      - ${PORT}:80

