name: Production - Server/Client Build/Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
  deploy:
    name: Deploy to FMD
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_NAME }}
        password: ${{ secrets.SERVER_PASS }}
        port: ${{ secrets.SERVER_PORT }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.SERVER_NAME }}
        proxy_password: ${{ secrets.SERVER_PASS }}
        proxy_port: ${{ secrets.SERVER_PORT }}
        script: |
          cd wise_docs
          git pull
          docker-compose up -d --build
          